// Generates migrations/0002_reference_data.sql: the streams, districts and subjects the live D1 database needs so
// student rows can reference them (foreign keys). Source = the compiled rulebook, so D1 holds exactly the codes the
// API validates against. Re-run only to regenerate before 0002 is first applied; after that, changes need a new migration.
// Run from the repo root:  node tools/seed/reference-sql.ts
import fs from 'node:fs';
import path from 'node:path';
import { ARTS_BASKET } from '../../shared/rules.ts';

const ROOT = path.resolve(import.meta.dirname, '..', '..');
const book = JSON.parse(fs.readFileSync(path.join(ROOT, 'worker', 'generated', 'rulebook-2025-2026.json'), 'utf8')) as {
  streams: { code: string; name: string }[];
  districts: { code: string; name: string; disadvantaged: boolean }[];
  subjects: { code: string; name: string }[];
  generatedAt: string;
};
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = (xs: string[]) => xs.map(x => `  (${x})`).join(',\n');

const sql = `-- ZedPath D1 migration 0002: reference data (streams, districts, subjects).
-- GENERATED by tools/seed/reference-sql.ts from worker/generated/rulebook-2025-2026.json (built ${book.generatedAt}).
-- Do not edit by hand. Source documents: UGC handbook 2025/26 (subjects, streams), UGC cut-off table 2025/26 (districts).

INSERT INTO stream (stream_code, name_en) VALUES
${rows(book.streams.map(s => `${q(s.code)}, ${q(s.name)}`))};

INSERT INTO district (district_code, name_en, is_disadvantaged) VALUES
${rows(book.districts.map(d => `${q(d.code)}, ${q(d.name)}, ${d.disadvantaged ? 1 : 0}`))};

INSERT INTO subject (subject_code, name_en, arts_basket) VALUES
${rows(book.subjects.map(s => `${q(s.code)}, ${q(s.name)}, ${ARTS_BASKET[s.code] ?? 'NULL'}`))};
`;
const out = path.join(ROOT, 'migrations', '0002_reference_data.sql');
fs.writeFileSync(out, sql);
console.log(`wrote ${path.relative(ROOT, out)}: ${book.streams.length} streams, ${book.districts.length} districts, ${book.subjects.length} subjects`);
